spring.application.name=Consumer

server.port=8081

spring.redis.host=localhost
spring.redis.port=6379
brewery-data.stream.key=brewery_stream

spring.datasource.url=jdbc:postgresql://localhost:5432/RedisStreamsDB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

